升级 docker 19.03

diff --git a/node/Dockerfile b/node/Dockerfile
--- a/node/Dockerfile
+++ b/node/Dockerfile
@@ -2,9 +2,9 @@
 FROM node:lts-alpine
 
 # --- Begin docker ---
-# from https://github.com/docker-library/docker/blob/master/18.09/Dockerfile
+# from https://github.com/docker-library/docker/blob/master/19.03/Dockerfile
 RUN apk add --no-cache \
-		ca-certificates
+	ca-certificates
 
 # set up nsswitch.conf for Go's "netgo" implementation (which Docker explicitly uses)
 # - https://github.com/docker/docker-ce/blob/v17.09.0-ce/components/engine/hack/make.sh#L149
@@ -13,33 +13,36 @@ RUN apk add --no-cache \
 RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
 
 ENV DOCKER_CHANNEL stable
-ENV DOCKER_VERSION 18.09.0
+ENV DOCKER_VERSION 19.03.0
 # TODO ENV DOCKER_SHA256
 # https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
 # (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
 
 RUN set -eux; \
 	\
-# this "case" statement is generated via "update.sh"
+	# this "case" statement is generated via "update.sh"
 	apkArch="$(apk --print-arch)"; \
 	case "$apkArch" in \
-		x86_64) dockerArch='x86_64' ;; \
-		armhf) dockerArch='armel' ;; \
-		aarch64) dockerArch='aarch64' ;; \
-		ppc64le) dockerArch='ppc64le' ;; \
-		s390x) dockerArch='s390x' ;; \
-		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	# amd64
+	x86_64) dockerArch='x86_64' ;; \
+	# arm32v6
+	armhf) dockerArch='armel' ;; \
+	# arm32v7
+	armv7) dockerArch='armhf' ;; \
+	# arm64v8
+	aarch64) dockerArch='aarch64' ;; \
+	*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
 	esac; \
 	\
 	if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
-		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
-		exit 1; \
+	echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${dockerArch}'"; \
+	exit 1; \
 	fi; \
 	\
 	tar --extract \
-		--file docker.tgz \
-		--strip-components 1 \
-		--directory /usr/local/bin/ \
+	--file docker.tgz \
+	--strip-components 1 \
+	--directory /usr/local/bin/ \
 	; \
 	rm docker.tgz; \
 	\
@@ -49,15 +52,21 @@ RUN set -eux; \
 COPY modprobe.sh /usr/local/bin/modprobe
 COPY docker-entrypoint.sh /usr/local/bin/
 
+# https://github.com/docker-library/docker/pull/166
+#   dockerd-entrypoint.sh uses DOCKER_TLS_CERTDIR for auto-generating TLS certificates
+#   docker-entrypoint.sh uses DOCKER_TLS_CERTDIR for auto-setting DOCKER_TLS_VERIFY and DOCKER_CERT_PATH
+# (For this to work, at least the "client" subdirectory of this path needs to be shared between the client and server containers via a volume, "docker cp", or other means of data sharing.)
+ENV DOCKER_TLS_CERTDIR=/certs
+
 ENTRYPOINT ["docker-entrypoint.sh"]
 CMD ["sh"]
 # --- End docker ---
 
 # --- Begin docker:git ---
-# from https://github.com/docker-library/docker/blob/master/18.09/git/Dockerfile
+# from https://github.com/docker-library/docker/blob/master/19.03/git/Dockerfile
 RUN apk add --no-cache \
-		git \
-		openssh-client
+	git \
+	openssh-client
 # --- End docker:git ---
 
 RUN echo "Asia/Shanghai" > /etc/timezone
